third

diff --git a/week7-master/JenkinsFile b/week7-master/JenkinsFile
--- a/week7-master/JenkinsFile
+++ b/week7-master/JenkinsFile
@@ -1,27 +1,29 @@
-pipeline{
-	agent any
-	stages{
-	stage('Build'){
-	steps{
-	echo "Build Docker Image"
-	bat "docker build -t mywebapp ."
-	}
-	}
-	stage('Run'){
-	steps{
-	echo "Run application in Docker Container"
-	bat "docker rm -f mycontainer || exit 0"
-	bat "docker run -d -p 5001:5001 --name mycontainer mywebapp"
-	}
-	}
-	}
-	post{
-	success{
-	echo 'Pipeline finished successfully!'
-	}
-	failure{
-	echo 'Pipeline failed.Please check the logs'
-	}
-	
-	}
+pipeline {
+    agent any
+
+    stages {
+        stage('Build') {
+            steps {
+                echo "Build Docker Image"
+                bat "docker build -t mywebapp ."
+            }
+        }
+
+        stage('Run') {
+            steps {
+                echo "Run application in Docker Container"
+                bat "docker rm -f mycontainer || exit 0"
+                bat "docker run -d -p 5001:5001 --name mycontainer mywebapp"
+            }
+        }
+    }
+
+    post {
+        success {
+            echo 'Pipeline finished successfully!'
+        }
+        failure {
+            echo 'Pipeline failed. Please check the logs.'
+        }
+    }
 }
